"use client";

import { HeroSection } from "@/components/HeroSection";
import { GlassCard } from "@/components/GlassCard";
import { GoldButton } from "@/components/GoldButton";
import { SectionHeading } from "@/components/SectionHeading";
import { useState, useEffect } from "react";
import { 
  Activity,
  ExternalLink,
  TrendingUp,
  TrendingDown,
  Clock,
  Bell,
  Zap,
  BarChart3,
  Globe,
  Shield,
  CheckCircle,
  ArrowRight,
  RefreshCw
} from "lucide-react";

const liveSignals = [
  { pair: "XAU/USD", type: "BUY", entry: "2342.50", target: "2368.00", stop: "2330.00", profit: "+$2,550", winRate: 87, timestamp: "2 min ago" },
  { pair: "EUR/USD", type: "SELL", entry: "1.0892", target: "1.0820", stop: "1.0920", profit: "+$720", winRate: 84, timestamp: "5 min ago" },
  { pair: "BTC/USD", type: "BUY", entry: "67,450", target: "71,200", stop: "65,800", profit: "+$3,750", winRate: 82, timestamp: "12 min ago" },
  { pair: "GBP/JPY", type: "BUY", entry: "192.45", target: "194.80", stop: "191.20", profit: "+$1,180", winRate: 86, timestamp: "18 min ago" },
  { pair: "ETH/USD", type: "SELL", entry: "3,420", target: "3,180", stop: "3,520", profit: "+$2,400", winRate: 85, timestamp: "25 min ago" },
  { pair: "USD/JPY", type: "BUY", entry: "154.80", target: "156.20", stop: "153.90", profit: "+$890", winRate: 88, timestamp: "32 min ago" },
];

const cryptoScans = [
  { coin: "BTC", signal: "Strong Buy", change: "+3.2%", volume: "High", pattern: "Bullish Flag" },
  { coin: "ETH", signal: "Buy", change: "+2.8%", volume: "Medium", pattern: "Ascending Triangle" },
  { coin: "SOL", signal: "Strong Buy", change: "+5.1%", volume: "Very High", pattern: "Breakout" },
  { coin: "BNB", signal: "Hold", change: "+0.5%", volume: "Low", pattern: "Consolidation" },
  { coin: "XRP", signal: "Buy", change: "+1.9%", volume: "Medium", pattern: "Inverse H&S" },
  { coin: "ADA", signal: "Strong Buy", change: "+4.7%", volume: "High", pattern: "Cup & Handle" },
];

const features = [
  {
    icon: Activity,
    title: "AI Signal Scanner",
    description: "Our AI analyzes 100+ pairs across forex, crypto, and indices in real-time to identify high-probability setups.",
  },
  {
    icon: Bell,
    title: "Instant Alerts",
    description: "Receive signals directly to your phone, email, or Telegram within seconds of detection.",
  },
  {
    icon: Zap,
    title: "Auto-Trading",
    description: "Connect your MT4/MT5 account for fully automated trade execution based on our signals.",
  },
  {
    icon: BarChart3,
    title: "Performance Analytics",
    description: "Track your trading performance with detailed analytics and customizable reports.",
  },
];

export default function SignalsPage() {
  const [currentSignal, setCurrentSignal] = useState(0);
  const [isRefreshing, setIsRefreshing] = useState(false);

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentSignal((prev) => (prev + 1) % liveSignals.length);
    }, 5000);
    return () => clearInterval(interval);
  }, []);

  const handleRefresh = () => {
    setIsRefreshing(true);
    setTimeout(() => setIsRefreshing(false), 1000);
  };

  return (
    <>
      <HeroSection
        subtitle="AI-Powered Trading Signals"
        title="Precision Signals, Powered by AI"
        description="Experience the power of artificial intelligence analyzing markets 24/7. Get real-time signals with 87%+ win rate across forex, crypto, and indices."
        size="md"
        showLogo={false}
        actions={{
          primary: { label: "Get Instant Access", href: "https://infinitysignals.net", external: true },
        }}
      />

      {/* Live Signals Section */}
      <section className="section-padding">
        <div className="max-w-7xl mx-auto">
          <div className="flex items-center justify-between mb-8">
            <SectionHeading
              label="Live Feed"
              title="Real-Time AI Signals"
              description="Signals generated by our AI algorithm every minute"
              align="left"
              className="mb-0"
            />
            <button
              onClick={handleRefresh}
              className="p-2 rounded-full bg-gold-400/10 border border-gold-400/20 text-gold-400 hover:bg-gold-400/20 transition-all"
            >
              <RefreshCw className={`w-5 h-5 ${isRefreshing ? 'animate-spin' : ''}`} />
            </button>
          </div>

          {/* Featured Signal */}
          <GlassCard glow className="mb-8 border border-gold-400/30">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-3">
                <div className="w-3 h-3 rounded-full bg-emerald-500 animate-pulse" />
                <span className="text-gold-400 font-medium">FEATURED SIGNAL</span>
              </div>
              <div className="flex items-center gap-2 text-gold-300/60 text-sm">
                <Clock className="w-4 h-4" />
                {liveSignals[currentSignal].timestamp}
              </div>
            </div>

            <div className="grid md:grid-cols-6 gap-4 items-center">
              <div>
                <span className="text-gold-300/50 text-xs">Pair</span>
                <p className="text-gold-100 text-xl font-bold">{liveSignals[currentSignal].pair}</p>
              </div>
              <div>
                <span className="text-gold-300/50 text-xs">Type</span>
                <p className={`text-xl font-bold ${liveSignals[currentSignal].type === 'BUY' ? 'text-emerald-500' : 'text-red-500'}`}>
                  {liveSignals[currentSignal].type}
                </p>
              </div>
              <div>
                <span className="text-gold-300/50 text-xs">Entry</span>
                <p className="text-gold-100 font-semibold">{liveSignals[currentSignal].entry}</p>
              </div>
              <div>
                <span className="text-gold-300/50 text-xs">Take Profit</span>
                <p className="text-emerald-500 font-semibold">{liveSignals[currentSignal].target}</p>
              </div>
              <div>
                <span className="text-gold-300/50 text-xs">Stop Loss</span>
                <p className="text-red-400 font-semibold">{liveSignals[currentSignal].stop}</p>
              </div>
              <div className="text-right">
                <span className="text-gold-300/50 text-xs">Potential Profit</span>
                <p className="text-2xl font-bold text-emerald-400">{liveSignals[currentSignal].profit}</p>
              </div>
            </div>

            <div className="flex justify-center gap-2 mt-4">
              {liveSignals.map((_, index) => (
                <div
                  key={index}
                  className={`h-1.5 rounded-full transition-all duration-300 ${
                    index === currentSignal ? "bg-gold-400 w-8" : "bg-gold-400/30 w-1.5"
                  }`}
                />
              ))}
            </div>
          </GlassCard>

          {/* Signal Table */}
          <GlassCard className="overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b border-gold-400/20">
                    <th className="text-left p-4 text-gold-400 font-medium">Pair</th>
                    <th className="text-left p-4 text-gold-400 font-medium">Signal</th>
                    <th className="text-left p-4 text-gold-400 font-medium">Entry</th>
                    <th className="text-left p-4 text-gold-400 font-medium">Target</th>
                    <th className="text-left p-4 text-gold-400 font-medium">Stop Loss</th>
                    <th className="text-left p-4 text-gold-400 font-medium">Win Rate</th>
                    <th className="text-left p-4 text-gold-400 font-medium">Time</th>
                  </tr>
                </thead>
                <tbody>
                  {liveSignals.map((signal, index) => (
                    <tr key={index} className="border-b border-gold-400/10 hover:bg-gold-400/5 transition-colors">
                      <td className="p-4 text-gold-100 font-medium">{signal.pair}</td>
                      <td className="p-4">
                        <span className={`flex items-center gap-1 ${signal.type === 'BUY' ? 'text-emerald-500' : 'text-red-500'}`}>
                          {signal.type === 'BUY' ? <TrendingUp className="w-4 h-4" /> : <TrendingDown className="w-4 h-4" />}
                          {signal.type}
                        </span>
                      </td>
                      <td className="p-4 text-gold-200/80">{signal.entry}</td>
                      <td className="p-4 text-emerald-500">{signal.target}</td>
                      <td className="p-4 text-red-400">{signal.stop}</td>
                      <td className="p-4">
                        <div className="flex items-center gap-2">
                          <div className="w-16 h-2 bg-navy-900 rounded-full overflow-hidden">
                            <div 
                              className="h-full bg-gradient-to-r from-gold-400 to-emerald-500 rounded-full"
                              style={{ width: `${signal.winRate}%` }}
                            />
                          </div>
                          <span className="text-gold-300/60 text-sm">{signal.winRate}%</span>
                        </div>
                      </td>
                      <td className="p-4 text-gold-300/50 text-sm">{signal.timestamp}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </GlassCard>
        </div>
      </section>

      {/* Crypto Scanner Section */}
      <section className="section-padding bg-gradient-to-b from-navy-900/20 to-onyx">
        <div className="max-w-7xl mx-auto">
          <SectionHeading
            label="Crypto Scanner"
            title="AI Crypto Market Scanner"
            description="Real-time analysis of top cryptocurrencies with pattern recognition"
          />

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
            {cryptoScans.map((crypto) => (
              <GlassCard key={crypto.coin} className="hover:border-gold-400/40 transition-all">
                <div className="flex items-center justify-between mb-3">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-full bg-gradient-to-br from-gold-400/20 to-navy-900 flex items-center justify-center">
                      <span className="text-gold-400 font-bold">{crypto.coin.charAt(0)}</span>
                    </div>
                    <div>
                      <span className="text-gold-100 font-medium">{crypto.coin}/USDT</span>
                      <p className="text-gold-300/50 text-xs">{crypto.pattern}</p>
                    </div>
                  </div>
                  <span className={`px-2 py-1 rounded text-xs font-medium ${
                    crypto.signal === 'Strong Buy' ? 'bg-emerald-500/20 text-emerald-400' :
                    crypto.signal === 'Buy' ? 'bg-emerald-500/10 text-emerald-400' :
                    'bg-gold-400/10 text-gold-400'
                  }`}>
                    {crypto.signal}
                  </span>
                </div>

                <div className="flex items-center justify-between text-sm">
                  <span className={crypto.change.startsWith('+') ? 'text-emerald-500' : 'text-red-500'}>
                    {crypto.change}
                  </span>
                  <span className="text-gold-300/50">Volume: {crypto.volume}</span>
                </div>
              </GlassCard>
            ))}
          </div>

          <div className="text-center mt-8">
            <GoldButton
              href="https://infinitysignals.net"
              external
              size="lg"
              icon={<ExternalLink className="w-5 h-5" />}
            >
              Access Full Scanner
            </GoldButton>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="section-padding">
        <div className="max-w-7xl mx-auto">
          <SectionHeading
            label="Platform Features"
            title="Everything You Need to Succeed"
          />

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {features.map((feature) => (
              <GlassCard key={feature.title} className="text-center">
                <div className="w-14 h-14 rounded-xl bg-gradient-to-br from-gold-400/20 to-navy-900/50 flex items-center justify-center mx-auto mb-4 border border-gold-400/20">
                  <feature.icon className="w-7 h-7 text-gold-400" />
                </div>
                <h3 className="text-lg font-serif text-gold-400 mb-2">{feature.title}</h3>
                <p className="text-gold-200/60 text-sm">{feature.description}</p>
              </GlassCard>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="section-padding bg-gradient-to-r from-navy-900/30 via-onyx to-navy-900/30">
        <div className="max-w-3xl mx-auto text-center">
          <GlassCard glow className="border border-gold-400/30">
            <Activity className="w-16 h-16 text-gold-400 mx-auto mb-4" />
            <h2 className="text-2xl md:text-3xl font-serif font-bold gold-gradient-text mb-4">
              Start Receiving AI Signals Today
            </h2>
            <p className="text-gold-200/70 mb-6">
              Join thousands of traders who trust our AI-powered signals for consistent profits.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <GoldButton
                href="https://infinitysignals.net"
                external
                size="lg"
                icon={<ExternalLink className="w-5 h-5" />}
              >
                Get Started Now
              </GoldButton>
              <span className="text-gold-300/50">No credit card required</span>
            </div>
          </GlassCard>
        </div>
      </section>
    </>
  );
}
